openapi: 3.0.4
info:
  title: API de Gestión de Contratistas, Vehículos y Personal
  description: API para la creación de contratistas, vehículos y personal y actualización de sus documentos. Asimismo, permite la eliminación, desactivación y activación de contratistas, vehículos y personal.

  version: 1.1.1
servers:
  - url: "https://{urlbase}/"
tags:
  - name: Peticiones de creacion y actualizacion de contratistas, vehiculos y staff
    description: |
      Descargar colección de Postman: <a class="sc-gmgFlS gDfmoL" target="_blank" href="https://testia-public-objects.s3.us-east-1.amazonaws.com/postman/API+Testia+-+Creaci%C3%B3n+y+Actualizaci%C3%B3n+de+Entidades.postman_collection.json.zip">Download</a><br><br>
      Endpoints relacionados con la creación y actualización de contratistas, vehículos y personal.
  - name: Gestión de entidades
    description: |
      Descargar colección de Postman: <a class="sc-gmgFlS gDfmoL" target="_blank" href="https://testia-public-objects.s3.us-east-1.amazonaws.com/postman/API+Testia+-+Eliminar+y+desactivar-activar+entidades.postman_collection.json.zip">Download</a><br><br>
      Endpoints relacionados con la gestión de entidades, permitiendo eliminar, desactivar y activar contratistas, vehículos y personal.
  - name: Editar entidades
    description: |
      Descargar colección de Postman: <a class="sc-gmgFlS gDfmoL" target="_blank" href="https://testia-public-objects.s3.us-east-1.amazonaws.com/postman/API+Testia+-+Editar+Entidades.postman_collection.json.zip">Download</a><br><br>
      Endpoints relacionados a la edición de datos de contratistas, vehículos y personal permitiendo cambiar datos como nombre, apellidos, correo, tipo de vehículo, etc.

paths:
  #? Peticiones de creacion y actualizacion de contratistas, vehiculos y staff
  /request/contractor:
    post:
      tags:
        - Peticiones de creacion y actualizacion de contratistas, vehiculos y staff
      summary: Crear o actualizar contratista
      description: Endpoint para crear y/o actualizar un contratista.
      operationId: createContractor
      parameters:
        - name: Apikey
          in: header
          description: ApiKey del usuario
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              allOf:
                - $ref: "#/components/schemas/ContractorDataDTO"
                - $ref: "#/components/schemas/ContractorMetadataArrayDTO"
                - type: object
                  properties:
                    files:
                      type: array
                      description: Los nombres y cantidad de los archivos debe coincidir con la metadata
                      items:
                        type: string
                        format: binary
            examples:
              JavaScript:
                summary: Ejemplo de creación de contratista
                description: Request para crear un contratista tipo empresa.
                value:
                  contractor:
                    contractorTypeId: 1
                    rut: "12345678-9"
                    businessName: "Empresa de Ejemplo S.A."
                    serviceTypeId: 1
                    reviewStartDate: "2024-12-01"
                    reviewEndDate: "2024-12-31"
                    reviewCompaniesId: []
                  contractorPartner:
                    rut: "98765432-1"
                    name: "Juan"
                    lastName: "Pérez"
                    email: "juan.perez@ejemplo.com"
                    phoneNumber: "+56912345678"
                  metadata:
                    - fileName: "documento1.pdf"
                      documentType: 16
                      period: "01/2025"
                    - fileName: "documento2.pdf"
                      documentType: 17
                  files:
                    - "documento1.pdf"
                    - "documento2.pdf"
              javascript-example:
                summary: Ejemplo en JavaScript
                description: Uso de `axios` para enviar una solicitud desde JavaScript.
                value: |
                  const axios = require('axios');
                  const FormData = require('form-data');
                  const fs = require('fs');

                  const formData = new FormData();
                  formData.append('contractor', JSON.stringify({
                    contractorTypeId: 1,
                    rut: '12345678-9',
                    businessName: 'Empresa de Ejemplo S.A.',
                    serviceTypeId: '1',
                    reviewStartDate: '2024-12-01',
                    reviewEndDate: '2024-12-31'
                  }));
                  formData.append('metadata', JSON.stringify([
                    {
                      fileName: 'documento1.pdf',
                      documentType: 16,
                      documentEntity: 1
                    },
                    {
                      fileName: 'documento2.pdf',
                      documentType: 17,
                      documentEntity: 2
                    }
                  ]));
                  formData.append('files', fs.createReadStream('documento1.pdf'));
                  formData.append('files', fs.createReadStream('documento2.pdf'));

                  axios.post('http://api.testia.cl/request/create-contractor', formData, {
                    headers: {
                      'Apikey': 'tu-apikey-aqui',
                      ...formData.getHeaders()
                    }
                  }).then(response => {
                    console.log(response.data);
                  }).catch(error => {
                    console.error(error);
                  });
              python-example:
                summary: Ejemplo en Python
                description: Uso de la librería `requests` para enviar una solicitud desde Python.
                value: |
                  import requests

                  url = "http://api.testia.cl/request/create-contractor"
                  headers = {
                      "Apikey": "tu-apikey-aqui"
                  }
                  files = {
                      'contractor': (None, '{"contractorTypeId": 1, "rut": "12345678-9", "businessName": "Empresa de Ejemplo S.A.", "serviceTypeId": "1", "reviewStartDate": "2024-12-01", "reviewEndDate": "2024-12-31"}', 'application/json'),
                      'metadata': (None, '[{"fileName": "documento1.pdf", "documentType": 16, "documentEntity": 1}, {"fileName": "documento2.pdf", "documentType": 17, "documentEntity": 2}]', 'application/json'),
                      'files': ('documento1.pdf', open('documento1.pdf', 'rb')),
                      'files': ('documento2.pdf', open('documento2.pdf', 'rb'))
                  }

                  response = requests.post(url, headers=headers, files=files)

                  print(response.status_code)
                  print(response.json())

      responses:
        "201":
          description: Solicitud de creación o actualización de contratista recibida
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        "400":
          description: Solicitud incorrecta
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        "401":
          description: No autorizado

  /request/vehicle/{contractorRut}:
    post:
      tags:
        - Peticiones de creacion y actualizacion de contratistas, vehiculos y staff
      summary: Crear o actualizar vehículo
      description: Endpoint para crear y/o actualizar un vehículo. Importante, solo se puede crear un vehículo o un acoplado a la vez.
      operationId: createVehicle
      parameters:
        - name: contractorRut
          in: path
          description: RUT del contratista asociado a la empresa. En formato con guion sin puntos
          required: true
          schema:
            type: string
        - name: Apikey
          in: header
          description: ApiKey del usuario
          required: true
          schema:
            type: string
        - name: unassigned
          in: query
          description: Esta query es enviada unicamente si se desea crear un vehiculo sin contratista asociado. Al enviar esta query se debe eliminar el rut del contratista como parametro.
          required: false
          schema:
            type: string
            examples: ["true"]
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              allOf:
                - $ref: "#/components/schemas/VehicleDataDto"
                - $ref: "#/components/schemas/VehicleMetadataArrayDTO"
                - type: object
                  properties:
                    files:
                      type: array
                      description: Los nombres y cantidad de los archivos debe coincidir con la metadata
                      items:
                        type: string
                        format: binary
            examples:
              JavaScript:
                summary: Ejemplo de creación de vehículo
                description: Request para crear un vehículo asociado a un contratista.
                value:
                  vehicle:
                    vehicleType: 3
                    patent: "ABCD12"
                  coupled:
                    coupledType: 1
                    patent: "EFGH45"
                  metadata:
                    - fileName: "documento1.pdf"
                      documentType: 24
                    - fileName: "documento2.pdf"
                      documentType: 25
                  files:
                    - "documento1.pdf"
                    - "documento2.pdf"
              javascript-example:
                summary: Ejemplo en JavaScript
                description: Uso de `axios` para enviar una solicitud desde JavaScript.
                value: |
                  const axios = require('axios');
                  const FormData = require('form-data');
                  const fs = require('fs');

                  const formData = new FormData();
                  formData.append('vehicle', JSON.stringify({
                    vehicleType: 3,
                    patent: 'ABCD-123'
                  }));
                  formData.append('coupled', JSON.stringify({
                    coupledType: 1,
                    patent: 'EFGH-456'
                  }));
                  formData.append('metadata', JSON.stringify([
                    {
                      fileName: 'documento1.pdf',
                      documentType: 24,
                      documentEntity: 3
                    },
                    {
                      fileName: 'documento2.pdf',
                      documentType: 25,
                      documentEntity: 5
                    }
                  ]));
                  formData.append('files', fs.createReadStream('documento1.pdf'));
                  formData.append('files', fs.createReadStream('documento2.pdf'));

                  axios.post('http://api.testia.cl/request/create-vehicle/12345678-9', formData, {
                    headers: {
                      'Apikey': 'tu-apikey-aqui',
                      ...formData.getHeaders()
                    }
                  }).then(response => {
                    console.log(response.data);
                  }).catch(error => {
                    console.error(error);
                  });
              python-example:
                summary: Ejemplo en Python
                description: Uso de la librería `requests` para enviar una solicitud desde Python.
                value: |
                  import requests

                  url = "http://api.testia.cl/request/create-vehicle/12345678-9"
                  headers = {
                      "Apikey": "tu-apikey-aqui"
                  }
                  files = {
                      'vehicle': (None, '{"vehicleType": 3, "patent": "ABCD-123"}', 'application/json'),
                      'coupled': (None, '{"coupledType": 1, "patent": "EFGH-456"}', 'application/json'),
                      'metadata': (None, '[{"fileName": "documento1.pdf", "documentType": 24, "documentEntity": 3}, {"fileName": "documento2.pdf", "documentType": 25, "documentEntity": 5}]', 'application/json'),
                      'files': ('documento1.pdf', open('documento1.pdf', 'rb')),
                      'files': ('documento2.pdf', open('documento2.pdf', 'rb'))
                  }

                  response = requests.post(url, headers=headers, files=files)

                  print(response.status_code)
                  print(response.json())
      responses:
        "201":
          description: Solicitud de creación o actualizacion de vehículo recibida
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        "400":
          description: Solicitud incorrecta
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        "401":
          description: No autorizado

  /request/staff/{contractorRut}:
    post:
      tags:
        - Peticiones de creacion y actualizacion de contratistas, vehiculos y staff
      summary: Crear o actualizar personal
      description: Endpoint para crear y/o actualizar personal.
      operationId: createStaff
      parameters:
        - name: contractorRut
          in: path
          description: RUT del contratista asociado a la empresa. En formato con guion sin puntos
          required: true
          schema:
            type: string
        - name: Apikey
          in: header
          description: ApiKey del usuario
          required: true
          schema:
            type: string
        - name: unassigned
          in: query
          description: Esta query es enviada unicamente si se desea crear un staff sin contratista asociado. Al enviar esta query se debe eliminar el rut del contratista como parametro.
          required: false
          schema:
            type: string
            examples: ["true"]
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              allOf:
                - $ref: "#/components/schemas/StaffDataDto"
                - $ref: "#/components/schemas/StaffMetadataArrayDTO"
                - type: object
                  properties:
                    files:
                      type: array
                      description: Los nombres y cantidad de los archivos debe coincidir con la metadata
                      items:
                        type: string
                        format: binary
            examples:
              JavaScript:
                summary: Ejemplo de creación de personal
                description: Request para crear personal asociado a un contratista.
                value:
                  staff:
                    name: "Carlos"
                    lastName: "Sánchez"
                    mothersLastName: "Pérez"
                    rut: "11222333-4"
                    staffType: 1
                  # vehicleStaff:
                  #   vehiclePatents:
                  #     - "ABCD12"
                  #     - "EFGH45"
                  metadata:
                    - fileName: "documento1.pdf"
                      documentType: 30
                      side: "frontal"
                    - fileName: "documento2.pdf"
                      documentType: 30
                      side: "trasera"
                    - fileName: "documento3.pdf"
                      documentType: 32
                  files:
                    - "documento1.pdf"
                    - "documento2.pdf"
                    - "documento3.pdf"
              javascript-example:
                summary: Ejemplo en JavaScript
                description: Uso de `axios` para enviar una solicitud desde JavaScript.
                value: |
                  const axios = require('axios');
                  const FormData = require('form-data');
                  const fs = require('fs');

                  const formData = new FormData();
                  formData.append('staff', JSON.stringify({
                    name: 'Carlos',
                    lastName: 'Sánchez',
                    mothersLastName: 'Pérez',
                    rut: '11222333-4',
                    staffType: '1'
                  }));
                  formData.append('metadata', JSON.stringify([
                    {
                      fileName: 'documento1.pdf',
                      documentType: 30,
                      documentEntity: 4
                    },
                    {
                      fileName: 'documento2.pdf',
                      documentType: 31,
                      documentEntity: 4
                    }
                  ]));
                  formData.append('files', fs.createReadStream('documento1.pdf'));
                  formData.append('files', fs.createReadStream('documento2.pdf'));

                  axios.post('http://api.testia.cl/request/create-staff/12345678-9', formData, {
                    headers: {
                      'Apikey': 'tu-apikey-aqui',
                      ...formData.getHeaders()
                    }
                  }).then(response => {
                    console.log(response.data);
                  }).catch(error => {
                    console.error(error);
                  });
              python-example:
                summary: Ejemplo en Python
                description: Uso de la librería `requests` para enviar una solicitud desde Python.
                value: |
                  import requests

                  url = "http://api.testia.cl/request/create-staff/12345678-9"
                  headers = {
                      "Apikey": "tu-apikey-aqui"
                  }
                  files = {
                      'staff': (None, '{"name": "Carlos", "lastName": "Sánchez", "mothersLastName": "Pérez", "rut": "11222333-4", "staffType": "1"}', 'application/json'),
                      'vehicleStaff': (None, '{"staffRut": "11222333-4", "vehiclePatents": ["ABCD-123", "EFGH-456"]}', 'application/json'),
                      'metadata': (None, '[{"fileName": "documento1.pdf", "documentType": 30, "documentEntity": 4}, {"fileName": "documento2.pdf", "documentType": 31, "documentEntity": 4}]', 'application/json'),
                      'files': ('documento1.pdf', open('documento1.pdf', 'rb')),
                      'files': ('documento2.pdf', open('documento2.pdf', 'rb'))
                  }

                  response = requests.post(url, headers=headers, files=files)

                  print(response.status_code)
                  print(response.json())
      responses:
        "201":
          description: Solicitud de creación de personal recibida
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        "400":
          description: Solicitud incorrecta
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        "401":
          description: No autorizado

  #? Gestion y edicion de entidades
  /contractor/{contractorRut}/status:
    patch:
      tags:
        - Gestión de entidades
      summary: Desactivar o activar contratista
      description: Endpoint para desactivar o activar un contratista.
      parameters:
        - name: Apikey
          in: header
          description: ApiKey del usuario
          required: true
          schema:
            type: string
        - name: contractorRut
          in: path
          description: RUT del contratista asociado a la empresa. En formato con guion sin puntos
          required: true
          schema:
            type: string

      responses:
        "200":
          description: Solicitud de desactivar o activar de contratista
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        "400":
          description: Solicitud incorrecta
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        "401":
          description: No autorizado

  /contractor/{contractorRut}:
    delete:
      tags:
        - Gestión de entidades
      summary: Elminar contratista
      description: Endpoint para eliminar un contratista.
      parameters:
        - name: Apikey
          in: header
          description: ApiKey del usuario
          required: true
          schema:
            type: string
        - name: contractorRut
          in: path
          description: RUT del contratista asociado a la empresa. En formato con guion sin puntos
          required: true
          schema:
            type: string

      responses:
        "200":
          description: Se elimino contratista con exito
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        "400":
          description: Solicitud incorrecta
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        "401":
          description: No autorizado

    patch:
      tags:
        - Editar entidades
      summary: Editar contratista
      description: Endpoint para editar los datos de un contratista.
      parameters:
        - name: Apikey
          in: header
          description: ApiKey del usuario
          required: true
          schema:
            type: string
        - name: contractorRut
          in: path
          description: RUT del contratista a editar. En formato con guion sin puntos
          required: true
          schema:
            type: string
      requestBody:
        description: |
          Se pueden editar los siguientes campos del contratista, enviar únicamente los deseados:
        required: false
        content:
          JSON:
            schema:
              allOf:
                - $ref: "#/components/schemas/ContractorUpdateDTO"

      responses:
        "200":
          description: Se edito el contratista con exito
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        "400":
          description: Solicitud incorrecta
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        "401":
          description: No autorizado

  /contractor/{contractorRut}/vehicle/{plate}/status:
    patch:
      tags:
        - Gestión de entidades
      summary: Desactivar o activar vehiculo
      description: Endpoint para desactivar o activar un vehiculo asociado a un contratista. Para gestionar un vehiculo independiente, omitir el path "/contractor/contractorRut".
      parameters:
        - name: Apikey
          in: header
          description: ApiKey del usuario
          required: true
          schema:
            type: string
        - name: contractorRut
          in: path
          description: RUT del contratista donde se encuentra el vehiculo. En formato con guion sin puntos
          required: false
          schema:
            type: string
        - name: plate
          in: path
          description: Patente del vehiculo
          required: true
          schema:
            type: string

      responses:
        "200":
          description: Solicitud de desactivar o activar de entidad
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        "400":
          description: Solicitud incorrecta
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        "401":
          description: No autorizado

  /contractor/{contractorRut}/vehicle/{plate}:
    delete:
      tags:
        - Gestión de entidades
      summary: Elminar vehiculo
      description: Endpoint para eliminar un vehiculo asociado a un contratista. Para gestionar un vehiculo independiente, omitir el path "/contractor/contractorRut".
      parameters:
        - name: Apikey
          in: header
          description: ApiKey del usuario
          required: true
          schema:
            type: string
        - name: contractorRut
          in: path
          description: RUT del contratista donde se encuentra el vehiculo. En formato con guion sin puntos
          required: false
          schema:
            type: string
        - name: plate
          in: path
          description: Patente del vehiculo a eliminar.
          required: true
          schema:
            type: string

      responses:
        "200":
          description: Se elimino entidad con exito
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        "400":
          description: Solicitud incorrecta
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        "401":
          description: No autorizado

    patch:
      tags:
        - Editar entidades
      summary: Editar vehiculo
      description: Endpoint para editar un vehiculo asociado a un contratista. Para editar un vehiculo independiente, omitir el path "/contractor/contractorRut".
      parameters:
        - name: apikey
          in: header
          description: ApiKey del usuario
          required: true
          schema:
            type: string
        - name: contractorRut
          in: path
          description: RUT del contratista donde se encuentra el vehiculo. En formato con guion sin puntos
          required: false
          schema:
            type: string
        - name: plate
          in: path
          description: Patente del vehiculo a editar.
          required: true
          schema:
            type: string
      requestBody:
        description: |
          Se pueden editar los siguientes campos del vehículo:
        required: false
        content:
          JSON:
            schema:
              allOf:
                - $ref: "#/components/schemas/VehicleUpdateDTO"

      responses:
        "200":
          description: Se edito la entidad con exito
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        "400":
          description: Solicitud incorrecta
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        "401":
          description: No autorizado

  /contractor/{contractorRut}/staff/{staffRut}/status:
    patch:
      tags:
        - Gestión de entidades
      summary: Desactivar o activar personal
      description: Endpoint para desactivar o activar un personal asociado a un contratista. Para gestionar un personal independiente, omitir el path "/contractor/contractorRut".
      parameters:
        - name: Apikey
          in: header
          description: ApiKey del usuario
          required: true
          schema:
            type: string
        - name: contractorRut
          in: path
          description: RUT del contratista donde se encuentra el vehiculo. En formato con guion sin puntos
          required: false
          schema:
            type: string
        - name: staffRut
          in: path
          description: RUT del personal a eliminar. En formato con guion sin puntos
          required: true
          schema:
            type: string

      responses:
        "200":
          description: Solicitud de desactivar o activar entidad
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        "400":
          description: Solicitud incorrecta
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        "401":
          description: No autorizado

  /contractor/{contractorRut}/staff/{staffRut}:
    delete:
      tags:
        - Gestión de entidades
      summary: Elminar personal
      description: Endpoint para eliminar un personal asociado a un contratista. Para gestionar un personal independiente, omitir el path "/contractor/contractorRut".
      parameters:
        - name: Apikey
          in: header
          description: ApiKey del usuario
          required: true
          schema:
            type: string
        - name: contractorRut
          in: path
          description: RUT del contratista donde se encuentra el vehiculo. En formato con guion sin puntos
          required: false
          schema:
            type: string
        - name: staffRut
          in: path
          description: RUT del personal a eliminar. En formato con guion sin puntos
          required: true
          schema:
            type: string

      responses:
        "200":
          description: Se elimino la entidad con exito
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        "400":
          description: Solicitud incorrecta
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        "401":
          description: No autorizado

    patch:
      tags:
        - Editar entidades
      summary: Editar personal
      description: Endpoint para editar un personal asociado a un contratista. Para editar un personal independiente, omitir el path "/contractor/contractorRut".
      parameters:
        - name: apikey
          in: header
          description: ApiKey del usuario
          required: true
          schema:
            type: string
        - name: contractorRut
          in: path
          description: RUT del contratista donde se encuentra el personal. En formato con guion sin puntos
          required: false
          schema:
            type: string
        - name: staffRut
          in: path
          description: RUT del personal a editar.
          required: true
          schema:
            type: string
      requestBody:
        description: |
          Se pueden editar los siguientes campos del personal, enviar únicamente los deseados:
        required: false
        content:
          JSON:
            schema:
              allOf:
                - $ref: "#/components/schemas/StaffUpdateDTO"

      responses:
        "200":
          description: Se edito la entidad con exito
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        "400":
          description: Solicitud incorrecta
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        "401":
          description: No autorizado

components:
  schemas:
    ContractorDataDTO:
      type: object
      properties:
        contractor:
          type: object
          description: Datos del contratista. Para actualizar, enviar unicamente el campo rut (Solo se permite actualizar documentos)
          properties:
            contractorTypeId:
              type: number
              description: |
                ID del tipo de contratista: 
                - Tipo "1" para Empresa
                - Tipo "2" para Persona natural
            rut:
              type: string
              description: RUT del contratista para crear o actualizar en formato con guiones sin puntos
            businessName:
              type: string
              description: Nombre de la contratista. Obligatorio cuando sea tipo "1" (Empresa)
            name:
              type: string
              description: Nombre del contratista. Obligatorio cuando sea tipo "2" (Persona natural)
            lastName:
              type: string
              description: Apellido paterno del contratista. Obligatorio cuando sea tipo "2" (Persona natural)
            mothersLastName:
              type: string
              description: Apellido materno del contratista. Obligatorio cuando sea tipo "2" (Persona natural)
            serviceTypeId:
              type: number
              description: |
                ID del tipo de servicio del contratista.
                - Tipo "1" para Monitoreo: Clientes finales
                - Tipo "2" para Prospecto: Clientes potenciales (Con tiempo y funciones limitadas)
            reviewStartDate:
              type: date
              description: Fecha de inicio de la review en formato YYYY-MM-DD
            reviewEndDate:
              type: date
              description: Fecha de fin de la review en formato YYYY-MM-DD
            reviewCompaniesId:
              type: array of numbers
              description: Arreglo de numeros de empresas revisaras. En caso de no existir, enviar arreglo vacio.
          required:
            - rut
            - contractorTypeId
            - serviceTypeId
            - reviewStartDate
            - reviewEndDate
            - reviewCompaniesId

        contractorPartner:
          type: object
          description: Datos de la contraparte asociada al contratista
          properties:
            rut:
              type: string
              description: RUT de la contraparte asociado al contratista. Formato con guiones sin puntos
            name:
              type: string
              description: Nombre de la contraparte asociado al contratista
            lastName:
              type: string
              description: Apellido paterno de la contraparte asociado al contratista.
            mothersLastName:
              type: string
              description: Apellido materno de la contraparte asociado al contratista.
            email:
              type: string
              description: Correo de la contraparte asociado al contratista
            phoneNumber:
              type: string
              description: Telefono de la contraparte asociado al contratista
          required:
            - rut
            - name
            - lastName
            - mothersLastName
            - email
            - phoneNumber

    ContractorMetadataArrayDTO:
      type: object
      properties:
        metadata:
          description: Metadatos relacionados con los documentos del contratista
          type: array
          items:
            type: object
            properties:
              fileName:
                type: string
                description: Nombre del documento a subir
              side:
                type: string
                description: Para los documentType "30" y "31", se debe especificar y enviar el lado del documento por separado. Puede ser "frontal o "trasera" según el caso.
              documentType:
                type: number
                description: |
                  Identificador del tipo de documento a cargar.
                  - Para empresa:
                    - "16" F30 (Total pagos). Solo se permite formato PDF.
                    - "17" F30 - 1 (Pagos individuales). Solo se permite formato PDF.
                    - "18" Carpeta Tributaria
                  - Para persona natural:
                    - "30" Cedula de Identidad: Debe enviar ambas caras por separado para procesar el documento. Formatos permitidos: PDF, JPEG, PNG. **
                    - "31" Licencia de conducir: Debe enviar ambas caras por separado para procesar el documento. Formatos permitidos: PDF, JPEG, PNG. **
                    - "32" Certificado de Antecedentes. Solo se permite formato PDF.
                    - "33" Hoja de vida del conductor. Solo se permite formato PDF.

                  ** Si el documento viene con ambas caras en un sólo archivo, es válido enviar el mismo archivo para ambas caras de forma separada. Si, sólo se envía una cara, quedará a la espera de la otra cara.
              period:
                type: string
                description: Periodo del documento, maximo 6 meses inclusive. Solo para los documentType "16", "17" y "18". En formato MM/YYYY. Si no se envia, se tomará el mes anterior al actual.
            required:
              - fileName
              - documentType

    VehicleDataDto:
      type: object
      properties:
        vehicle:
          type: object
          description: Datos del vehiculo a crear.
            Para actualizar, enviar unicamente el campo patent del vehiculo o acoplado dentro de la propiedad vehicle (Solo se permite actualizar documentos)
          properties:
            vehicleType:
              type: number
              description: |
                ID del tipo de vehiculo
                - "1" Batea
                - "2" Cama baja
                - "3" Camión abierto
                - "4" Camión cerrado
                - "5" Camión pluma
                - "6" Cisterna
                - "7" Furgón
                - "8" Rampla abierta
                - "9" Rampla cerrada
                - "10" Refrigerado
                - "11" Semi baranda
                - "12" Sider
                - "13" Tracto
                - "14" Transportador de vehículos
                - "15" Utilitario
                - "16" Otro
            patent:
              type: string
              description: Patente del vehiculo para crear
          required:
            - vehicleType
            - patent

        coupled:
          type: object
          description: Datos del acoplado a crear. Puede crear un vehiculo o un acoplado o ambos al mismo tiempo.
          properties:
            coupledType:
              type: number
              description: |
                ID del tipo de acoplado
                - "1" Remolque
                - "2" Semirremolque
            patent:
              type: string
              description: Patente del acoplado para crear
            # reviewCompaniesId:
            #   type: number
            #   description: Fecha de fin de la review en formato YYYY-MM-DD
          required:
            - patent
            - coupledType

    VehicleMetadataArrayDTO:
      type: object
      properties:
        metadata:
          description: Metadatos relacionados con los documentos del vehiculo o acoplado
          type: array
          items:
            type: object
            properties:
              fileName:
                type: string
                description: Nombre del documento a subir
              documentType:
                type: number
                description: |
                  Identificador del tipo de documento a cargar.
                  - Para vehiculo y acoplado:
                    - "24" Permiso de circulacion
                    - "25" Revisión técnica
                    - "26" SOAP
                    - "28" Póliza de seguro
                    - "29" Pagos del seguro

                  Formatos permitidos: PDF, JPEG, PNG
              period:
                type: string
                description: Periodo del documento, maximo 6 meses inclusive. Solo para los documentType "29". En formato MM/YYYY. Si no se envia, se tomará el mes anterior al actual.
            required:
              - fileName
              - documentType

    StaffDataDto:
      type: object
      properties:
        staff:
          type: object
          description: Datos del personal a crear.
            Para actualizar, enviar unicamente el campo rut del personal (Solo se permite actualizar documentos)
          properties:
            name:
              type: string
              description: Nombre del personal para crear
            lastName:
              type: string
              description: Apellido paterno del personal para crear.
            mothersLastName:
              type: string
              description: Apellido materno del personal para crear.
            rut:
              type: string
              description: RUT del personal para crear. En formato con guiones y sin puntos
            staffType:
              type: number
              description: |
                Tipo de personal para crear
                  - "1" Chofer
                  - "2" Peoneta
                  - "3" Gruero
                  - "4" Encargado bodega
          required:
            - name
            - lastName
            - mothersLastName
            - rut
            - staffType

        # vehicleStaff:
        #   type: object
        #   description: Asociar un personal a un vehiculo o acoplado previamente existente
        #   properties:
        #     vehiclePatents:
        #       type: array
        #       items:
        #         type: string
        #       description: Patente del vehiculo para asociar
        #   required:
        #     - staffRut
        #     - vehiclePatents

    StaffMetadataArrayDTO:
      type: object
      properties:
        metadata:
          description: Metadatos relacionados con los documentos del personal
          type: array
          items:
            type: object
            properties:
              fileName:
                type: string
                description: Nombre del documento a subir
              side:
                type: string
                description: Para los documentType "30" y "31", se debe especificar y enviar el lado del documento por separado. Puede ser "frontal o "trasera" según el caso.
              documentType:
                type: number
                description: |
                  Identificador del tipo de documento a cargar.
                  - "30" Cedula de Identidad: Debe enviar ambas caras por separado para procesar el documento. Formatos permitidos: PDF, JPEG, PNG. **
                  - "31" Licencia de conducir: Debe enviar ambas caras por separado para procesar el documento. Formatos permitidos: PDF, JPEG, PNG. **
                  - "32" Certificado de Antecedentes. Solo se permite formato PDF.
                  - "33" Hoja de vida del conductor. Solo se permite formato PDF.

                  ** Si el documento viene con ambas caras en un sólo archivo, es válido enviar el mismo archivo para ambas caras de forma separada. Si, sólo se envía una cara, quedará a la espera de la otra cara.
            required:
              - fileName
              - documentType

    ContractorUpdateDTO:
      type: object
      properties:
        name:
          type: string
          description: Nuevo nombre de la contraparte del contratista a actualizar.
        lastName:
          type: string
          description: Nuevo apellido de la contraparte del contratista a actualizar.
        email:
          type: string
          description: Nuevo correo de la contraparte del contratista a actualizar.
        phoneNumber:
          type: string
          description: Nuevo teléfono de la contraparte del contratista a actualizar.
        serviceTypeId:
          type: number
          description: ID del tipo de servicio del contratista.

    VehicleUpdateDTO:
      type: object
      properties:
        vehicleType:
          type: number
          description: |
            IDs validos para actualizar vehículos:
            - "1" Batea
            - "2" Cama baja
            - "3" Camión abierto
            - "4" Camión cerrado
            - "5" Camión pluma
            - "6" Cisterna
            - "7" Furgón
            - "8" Rampla abierta
            - "9" Rampla cerrada
            - "10" Refrigerado
            - "11" Semi baranda
            - "12" Sider
            - "13" Tracto
            - "14" Transportador de vehículos
            - "15" Utilitario
            - "16" Otro

            IDs validos para actualizar acoplados:
            - "1" Remolque
            - "2" Semirremolque

    StaffUpdateDTO:
      type: object
      properties:
        name:
          type: string
          description: Nuevo nombre del personal a actualizar
        lastName:
          type: string
          description: Nuevo apellido paterno del personal a actualizar.
        mothersLastName:
          type: string
          description: Nuevo apellido materno del personal a actualizar.
        staffType:
          type: number
          description: |
            IDs validos para actualizar el personal:
            - "1" Chofer
            - "2" Peoneta
            - "3" Gruero
            - "4" Encargado bodega
